### ISSUE TITLE
Use quicktype as a library?

### ISSUE THREAD

**Issue by schani** [bitsol/quicktype-Azure-DB-Schema#7]
I'm one of the authors of quicktype.

You might have an easier time implementing your target language by using quicktype as a library, rather than making a full clone of it.  [Here's an example](https://github.com/quicktype/quicktype-custom-java-example) that shows how to supply your own target language when invoking quicktype that way.

We'd also love to hear about any issues you have.  Please feel free to file quicktype issues for things you think are needed for implementing new target languages.  If you want talk to us directly, please [join us on Slack](https://slackin-dnnovkeacz.now.sh).  Cheers!

**Comment by bitsol** [comment]
Hello @schani! I'm refactoring the project over here: https://github.com/bitsol/quicktype-AzureDBNodeSchema

**Comment by schani** [comment]
I just updated/fixed the Java customization example.  The branch of `quicktype` that it was referencing doesn't exist anymore.  Just use `master`.
